### ISSUE TITLE
Future support for creating Synthetic Browser test steps

### ISSUE THREAD

**Issue by IcyWednesdays** [pulumi/pulumi-datadog#112]
Hi,

We're doing some work with Synthetics Browser tests at the moment, and noticed the following note in the documentation:

> Some steps types (like steps involving elements) cannot be created, but they can be imported

Is there any plan to provide the ability for creating steps that require elements in the future? We're currently managing our Browser synthetics outside of code, so we're keen to understand if this is on the roadmap.

Cheers,
Matt

**Comment by pgavlin** [comment]
@stack72 do you have any context on this?

**Comment by stack72** [comment]
This requires an upgrade to v2.21.0 of the Datadog TF provider. that is in our current iteration plan
