### ISSUE TITLE
SyntheticsTest resource will always show diff of assertions with --refresh

### ISSUE THREAD

**Issue by williamsbdev** [pulumi/pulumi-datadog#143]
I'm going to preface this with the fact that I'm not sure if this is an issue in Pulumi or in Terraform and I'd appreciate some help in determining where I should seek help.

Every time we run a `pulumi preview --refresh --stack name --diff`, we will see that the assertions are being added. It feels like the `--refresh` option is not properly querying the API and representing the assertions when populating the state and doing the diff.

## Steps to reproduce

```
new datadog.SyntheticsTest(
  'some-name',
  {
    assertions: [
      {
        operator: 'lessThan',
        type: 'responseTime',
        target: responseTime,
      },
      {
        operator: 'is',
        type: 'statusCode',
        target: 200,
      }
    ],
    locations: ['aws:us-west-1'],
    message: pagerdutyMessage,
    'some-name',
    optionsList: {
      tickEvery: 300,
      minFailureDuration: 300,
      minLocationFailed: 1,
      followRedirects: true,
    },
    request: {
      method: 'GET',
      url: 'http://example.com',
      timeout: 30,
    },
    tags: defaultTags,
    type: 'api',
    subtype: 'http',
    status: 'live',
  }
)
```

1. Given the resource above
2. It has been deployed and no local changes have been made
3. Run the command `pulumi preview --refresh --stack name --diff`
4. You should see an update like the following:

```
~ assertions: [
    + [0]: {
        + operator  : "lessThan"
        + target    : 2000
        + type      : "responseTime"
    }
    + [1]: {
        + operator  : "is"
        + target    : 200
        + type      : "statusCode"
    }
]
```

Expected: There should be no updates made to the `SyntheticsTest` resource.
Actual: The `assertions` array always shows an update from an empty array to the array with our assertions.

**Comment by lukehoban** [comment]
> I'm going to preface this with the fact that I'm not sure if this is an issue in Pulumi or in Terraform and I'd appreciate some help in determining where I should seek help.

We'll likely need to verify whether this is also an issue in Terraform, and if so, report it to the upstream provider.  Else, it is possible it is a Pulumi-specific issue we could investigate.

**Comment by williamsbdev** [comment]
@lukehoban - Thank you so much for the reply! Sorry for the delay but here is the example Terraform project mimicking our Pulumi setup of the Synthetics API test. It's nearly identical to the first example on the Datadog provider in the Terraform registry.

https://github.com/williamsbdev/terraform-example-of-pulumi-datadog-synthetics

When I deployed it:

`terraform apply -var-file="variables.tfvars"`

Then ran:

`terraform plan -var-file="variables.tfvars"`

I did not get any weirdness where it was saying that it would update the `assertions` leading me to believe that Terraform is interacting with the API correctly but Pulumi seems to be the problem in this case.

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it?

**Comment by williamsbdev** [comment]
@mjeffryes - I'd completely forgot about this issue. I encountered this working for a client years ago (obviously) but haven't worked with them in over 2 years and I haven't used Datadog for any clients since so I can't speak to the relevancy of the issue anymore.

I think it is acceptable to close this issue and should I encounter it again, I'll either reopen or dig in further.

Thank you for circling back around to the issue.
