### ISSUE TITLE
Provider auth error links to Terraform docs instead of Pulumi docs

### ISSUE THREAD

**Issue by svangordon-fruit** [pulumi/pulumi-datadog#164]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Datadog provider with invalid auth config produces an error message referring to Terraform docs

### Steps to reproduce

1. Dependencies: `pulumi-datadog==4.5.0`, `pulumi==3.22.1`
2. Config set to something bogus:
```
❯ p config --show-secrets
KEY             VALUE
datadog:apiKey  asdf
datadog:appKey  asdf
```
3. Bare bones DataDog stack:
```
import pulumi_datadog as datadog

dashboard = datadog.Dashboard("Test Dashboard", layout_type="free", title="myDashboardWithoutAuth")
```
4. Run `pulumi preview`

Expected: Error message pointing to Pulumi docs (the [Configuring Credentials](https://www.pulumi.com/registry/packages/datadog/installation-configuration/#configuring-credentials) page, probably)
Actual: Error message pointing to Terraform docs
```
Diagnostics:
  datadog:index:Dashboard (Test Dashboard):
    error: 1 error occurred:
    	* Invalid or missing credentials provided to the Datadog Provider. Please confirm your API and APP keys are valid and are for the correct region, see https://www.terraform.io/docs/providers/datadog/ for more information on providing credentials for the Datadog Provider
```

The initial error is from here [DataDog/terraform-provider-datadog](https://github.com/DataDog/terraform-provider-datadog/blob/b7ad44483aa81b213e1d4053518c3435f8f4c2b5/datadog/provider.go#L248).

(As an aside, I'm not sure if it's my local network, but I'm seeing crazy long load times on https://www.pulumi.com/registry/packages/datadog/api-docs/dashboard/ , like ~45 seconds)

**Comment by mjeffryes** [comment]
This message is produced by the underlying terraform provider. While I agree it would be nice if we could point users to the pulumi doc instead, this logging behavior is aligned with the design (we'd much rather have all the details of these errors so users can resolve rather than suppressing them because they might reference terraform.
