### ISSUE TITLE
MonitorMonitorThresholdsArgs Use String instead of Floating Point Values

### ISSUE THREAD

**Issue by ggchan0** [pulumi/pulumi-datadog#229]
### What happened?

When using MonitorMonitorThresholdsArgs for creating Datadog Monitors, the value is a string instead of a floating point number. This is consistent with what is shown in the example, however is inconsistent with the documentation as well as Datadog's example.

Pulumi Example
<img width="960" alt="image" src="https://user-images.githubusercontent.com/9098217/222235967-317057e3-9f6f-49b5-a59f-83b36ece0f08.png">

Pulumi Documentation
<img width="941" alt="image" src="https://user-images.githubusercontent.com/9098217/222236059-8f069e38-efb8-438f-8719-b4291f04beac.png">

Datadog's Example
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/9098217/222236163-6ceb7b8e-5873-4170-aac9-cd1f638e8570.png">

If I were to supply a floating point number instead of a string, it somehow truncates it to an integer, and gives an error saying that the monitor threshold value is different from the one used in the query:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/9098217/222236785-7f9b97d0-ab35-4c50-be8d-27e8b03e48e5.png">

### Expected Behavior

When using a floating point value, Datadog Pulumi uses that value

### Steps to reproduce

Create a Datadog Monitor with floating point values for the Monitor thresholds like so:

```
foo = datadog.Monitor("foo",
    escalation_message="Escalation message @pagerduty",
    include_tags=True,
    message="Monitor triggered. Notify: @hipchat-channel",
    monitor_thresholds=datadog.MonitorMonitorThresholdsArgs(
        critical=4.5,
        warning=2.7,
    ),
    name="Name for monitor foo",
    query="avg(last_1h):avg:aws.ec2.cpu{environment:foo,host:foo} by {host} > 4",
    tags=[
        "foo:bar",
        "team:fooBar",
    ],
    type="metric alert")
```

Try and create the monitor

### Output of `pulumi about`

<img width="895" alt="image" src="https://user-images.githubusercontent.com/9098217/222238142-a2caa135-ea18-4e66-b150-00599cba2380.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @ggchan0, thanks for pointing this out. This is a bridged provider, which means we use the API surface defined by https://github.com/DataDog/terraform-provider-datadog. They have defined `MonitorMonitorThresholdsArgs.critical` as a `string`.

**Comment by ggchan0** [comment]
Gotcha makes sense, thanks for letting me know. Did not realize this was the case
