### ISSUE TITLE
SyntheticsTest docs is missing language chooser

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-datadog#242]
### What happened?

The [SyntheticsTest resource in the registry](https://www.pulumi.com/registry/packages/datadog/api-docs/syntheticstest/) is missing the language chooser. Note that this is probably an edge case that tfgen does not handle correctly:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/410614/231246622-da95660c-21b9-4770-8ed6-3dff7b464bc2.png">

### Expected Behavior

The language chooser should be present around the converted HCL.

### Steps to reproduce

n/a

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Closed via https://github.com/pulumi/pulumi-terraform-bridge/pull/1689. 

There's a followup bug on that resource's page now that I will file - but this particular issue has been fixed.
