### ISSUE TITLE
v4.18.0 produces error on `pulumi up` or `preview` using `config` for apiKey and appKey

### ISSUE THREAD

**Issue by magreenbaum** [pulumi/pulumi-datadog#276]
### What happened?

After upgrading to v4.18.0, using `datadog:apiKey` and `datadog:appKey` via pulumi configuration produces an error:
`error: rpc error: code = Unknown desc = config value 'apiKey' mismatch between servers 1 and a previous server`

This happens with existing config set and no other changes except for upgrading the provider version. 

If using environment variables instead, no error is produced and the command succeeds. This is a workaround. 

### Expected Behavior

Run `pulumi up` or `pulumi preview` with no issues. 

### Steps to reproduce

Upgrade to v4.18.0. If using pulumi config to set datadog app and api keys, no further change required. Otherwise, [per the docs](https://www.pulumi.com/registry/packages/datadog/installation-configuration/), set these with config:
```
pulumi config set datadog:apiKey XXXXXXXXXXXXXX --secret && pulumi config set datadog:appKey YYYYYYYYYYYYYY --secret
```
Run `pulumi up` or `pulumi preview` on a stack using this provider. 

### Output of `pulumi about`

```
CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME     VERSION
datadog  4.18.0

Host     
OS       darwin
Version  13.2.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ollaw** [comment]
Bumped into this one form Python with `v4.18.0`.

**Comment by aq17** [comment]
Hi @magreenbaum and @ollaw , we have a fix almost ready to go. We'll release a patch version once it's done.
In case you're curious, it's actually not datadog specific – it has to do with the upstream provider migrating to the new plugin framework. Your existing apikey should be good to keep using.

**Comment by aq17** [comment]
@magreenbaum @ollaw version `v4.18.1` is released, please let us know if this fixes the issue

**Comment by magreenbaum** [comment]
> @magreenbaum @ollaw version `v4.18.1` is released, please let us know if this fixes the issue

Thanks @aq17, `v4.18.1` fixed the issue.
