### ISSUE TITLE
Python SDK is missing classes/types shown in the documentation

### ISSUE THREAD

**Issue by mitchell-maler-ascendlearning-com** [pulumi/pulumi-datadog#289]
### What happened?

Trying to create a synthetic test based on the documentation in Python, but unable to follow due to missing classes.
For example, when setting this which is shown in the documentation
```pyton
options_list=datadog.SyntheticsTestOptionsListArgs(
```
Has the error "Cannot find reference 'SyntheticsTestOptionsListArgs' in '__init__.py'"

Looking at the code, those Types/Classes do not seem to exist.
https://github.com/pulumi/pulumi-datadog/blob/master/sdk/python/pulumi_datadog/synthetics_test.py

### Expected Behavior

The different Types outlined in the documentation be available for use.

### Steps to reproduce

options_list=pulumi_datadog.SyntheticsTestOptionsListArgs(),

### Output of `pulumi about`

$ pulumi about
CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
datadog       4.18.1

### Additional context

I believe we can get around this by passing a dict to the different arguments instead of trying to use the types, but we would rather use type instead when possible.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
I'm going to close this issue as stale.

Please feel free to reopen if needed.
