### ISSUE TITLE
Unable to create role-based AWS Integration dynamically

### ISSUE THREAD

**Issue by bfosberry** [pulumi/pulumi-datadog#305]
### What happened?

I am trying to connect a pulumi-provisioned AWS account with DD via a NewIntegration, however this is not working. Creating a new integration depends on having a role in place. Creating a long term role depends on having the external ID tied to the role, and getting the external ID depends on having the integration in place and configured. 

Resources cannot be edited to later modify the trust relationship to add in the external id, and the aws integration cannot be created successfully in a pending/error state. As such there is no clear path to a working integrtation within Pulumi

### Expected Behavior

It should be possible to create an AWS Account, Datadog Integration for that account, and the supporting role from within Pulumi without having to externally call the datadog APIs or modify AWS resources. 

I think the simplest way to do this is to ignore errors from the datadog API around role existence, or avoid other checks to ensure the integration is working. If there is a resource option or arg we can pass to achieve this that would be ideal. 

### Steps to reproduce

* Create an AWS account
* Add a new Datadog AWS integration (Should Error if role doesnt exist)

Or
* Create an AWS account
* Add a datadog policy
* Add a datadog role (with a temporary external id?)
* Add a policy-role-attachment
* Add a new Datadog AWS integration (Should error since external id doesnt match)

Or
* Create an AWS account
* Add a datadog policy
* Add a datadog role (with no external ID condition)
* Add a policy-role-attachment
* Add a new Datadog AWS integration (Should work but is wide open)
* Modify the role to change the trust relationship using the external ID returned (not possible)

### Output of `pulumi about`

[bfosberry@Brendans-MBP workload (bfosberry/dd-aws)]$ pulumi about
CLI
Version      3.63.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.35.0
datadog     4.18.1
go          unknown
kubernetes  3.24.3
mysql       3.1.0
random      4.13.2
tls         4.6.1

Host
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.20.3 darwin/arm64'

Current Stack: dev

TYPE                                                    URN
pulumi:providers:aws                                    urn:pulumi:dev::workload::pulumi:providers:aws::default
pulumi:pulumi:Stack                                     urn:pulumi:dev::workload::pulumi:pulumi:Stack::workload-dev
pkg:main:ShareVpc                                       urn:pulumi:dev::workload::pkg:main:ShareVpc::vpc
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0ed58c9ebd850f0e7-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0099e96f4ddc25c81-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0ed58c9ebd850f0e7-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0099e96f4ddc25c81-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0099e96f4ddc25c81-eksTag
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f2c36c93637a6969-eksTag
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f2c36c93637a6969-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0369494ad2c2fbefa-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0369494ad2c2fbefa-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f2c36c93637a6969-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f080f7197ed3501b-eksTag
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-02485d4adf8784b83-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f080f7197ed3501b-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f080f7197ed3501b-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-02485d4adf8784b83-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-011bd497bda4d7822-eksTag
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-011bd497bda4d7822-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0853e2146d4131e93-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-011bd497bda4d7822-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0853e2146d4131e93-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0368bc36f0dfd4f39-eksTag
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-013659e1cb620317b-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0368bc36f0dfd4f39-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-013659e1cb620317b-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0368bc36f0dfd4f39-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-042f7bf4183ed342e-eksTag
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0f9f8e40ebdef58a3-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-042f7bf4183ed342e-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0f9f8e40ebdef58a3-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-042f7bf4183ed342e-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0ac7e965ec278a110-eksTag
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0a4376e066387173e-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0ac7e965ec278a110-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0ac7e965ec278a110-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-0a4376e066387173e-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-07db7cd36e671355e-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f486d9b16285ce67-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f486d9b16285ce67-type
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::rtb-07db7cd36e671355e-name
aws:ec2/tag:Tag                                         urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/tag:Tag::subnet-0f486d9b16285ce67-eksTag
aws:ec2/securityGroup:SecurityGroup                     urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/securityGroup:SecurityGroup::database
aws:ec2/securityGroup:SecurityGroup                     urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/securityGroup:SecurityGroup::base
pkg:main:GithubIntegration                              urn:pulumi:dev::workload::pkg:main:GithubIntegration::gh-actions
aws:ec2/vpcEndpointService:VpcEndpointService           urn:pulumi:dev::workload::pkg:main:ShareVpc$aws:ec2/vpcEndpointService:VpcEndpointService::control-plane-endpoint-service
aws:s3/bucket:Bucket                                    urn:pulumi:dev::workload::aws:s3/bucket:Bucket::myapp-tenant-state
pulumi:providers:tls                                    urn:pulumi:dev::workload::pulumi:providers:tls::default
pkg:main:Database                                       urn:pulumi:dev::workload::pkg:main:Database::myapp-control-plane-db
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::aws:iam/policy:Policy::myapp-tenant-provisioning
aws:kms/key:Key                                         urn:pulumi:dev::workload::aws:kms/key:Key::controlplane-dbenvelopekey
aws:kms/key:Key                                         urn:pulumi:dev::workload::aws:kms/key:Key::controlplane-authtokenkey
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::aws:iam/policy:Policy::tenant-state-s3-policy
aws:s3/bucketOwnershipControls:BucketOwnershipControls  urn:pulumi:dev::workload::aws:s3/bucketOwnershipControls:BucketOwnershipControls::myapp-tenant-state-state-ownership
aws:rds/subnetGroup:SubnetGroup                         urn:pulumi:dev::workload::pkg:main:Database$aws:rds/subnetGroup:SubnetGroup::myapp-control-plane-db-subnet-group
aws:kms/alias:Alias                                     urn:pulumi:dev::workload::aws:kms/alias:Alias::controlplane-dbenvelopekey-alias
aws:kms/alias:Alias                                     urn:pulumi:dev::workload::aws:kms/alias:Alias::controlplane-authtokenkey-alias
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::aws:iam/policy:Policy::controlplane-kms-keys
aws:rds/instance:Instance                               urn:pulumi:dev::workload::pkg:main:Database$aws:rds/instance:Instance::myapp-control-plane-db-server
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::aws:iam/policy:Policy::eksCreator-policy
aws:iam/role:Role                                       urn:pulumi:dev::workload::aws:iam/role:Role::eksCreator
pulumi:providers:datadog                                urn:pulumi:dev::workload::pulumi:providers:datadog::default
pulumi:providers:mysql                                  urn:pulumi:dev::workload::pkg:main:Database$pulumi:providers:mysql::myapp-control-plane-db-mysql-db-provider
datadog:index/apiKey:ApiKey                             urn:pulumi:dev::workload::datadog:index/apiKey:ApiKey::workload-cluster-key-dev
aws:iam/openIdConnectProvider:OpenIdConnectProvider     urn:pulumi:dev::workload::pkg:main:GithubIntegration$aws:iam/openIdConnectProvider:OpenIdConnectProvider::gh-actions
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::aws:iam/rolePolicyAttachment:RolePolicyAttachment::eksCreator-policy-attachment
mysql:index/database:Database                           urn:pulumi:dev::workload::pkg:main:Database$mysql:index/database:Database::myapp-control-plane-db-mysql-db
aws:iam/role:Role                                       urn:pulumi:dev::workload::pkg:main:GithubIntegration$aws:iam/role:Role::gh-actions-role
mysql:index/user:User                                   urn:pulumi:dev::workload::pkg:main:Database$mysql:index/database:Database$mysql:index/user:User::myapp-control-plane-db-mysql-standard-user
mysql:index/grant:Grant                                 urn:pulumi:dev::workload::pkg:main:Database$mysql:index/database:Database$mysql:index/grant:Grant::myapp-control-plane-db-mysql-access-grant
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::pkg:main:Database$mysql:index/database:Database$mysql:index/user:User$aws:iam/policy:Policy::myapp-control-plane-db-standard-user-policy
pkg:main:KubernetesCluster                              urn:pulumi:dev::workload::pkg:main:KubernetesCluster::dev
pulumi:providers:aws                                    urn:pulumi:dev::workload::pulumi:providers:aws::eksCreatorProvider
pkg:main:eksState                                       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState::dev
pkg:containers:Registry                                 urn:pulumi:dev::workload::pkg:containers:Registry::private
pkg:main:TemporalDatabase                               urn:pulumi:dev::workload::pkg:main:TemporalDatabase::dev
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::pkg:main:KubernetesCluster$aws:iam/policy:Policy::dev-aws-lb-controller
pkg:main:ACMCertificate                                 urn:pulumi:dev::workload::pkg:main:ACMCertificate::corp
pkg:main:ACMCertificate                                 urn:pulumi:dev::workload::pkg:main:ACMCertificate::api
aws:route53/zone:Zone                                   urn:pulumi:dev::workload::aws:route53/zone:Zone::controlplane-agent
pkg:main:PackerIntegration                              urn:pulumi:dev::workload::pkg:main:PackerIntegration::packer-builds
aws:iam/role:Role                                       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:iam/role:Role::nodegroup-iam-role
aws:iam/role:Role                                       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:iam/role:Role::eks-iam-eksRole
aws:ec2/securityGroup:SecurityGroup                     urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:ec2/securityGroup:SecurityGroup::eks-private-access-sg
aws:ec2/securityGroup:SecurityGroup                     urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:ec2/securityGroup:SecurityGroup::dev-ng-security-group
aws:acm/certificate:Certificate                         urn:pulumi:dev::workload::pkg:main:ACMCertificate$aws:acm/certificate:Certificate::corp-cert
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::pkg:main:PackerIntegration$aws:iam/policy:Policy::PackerMin
aws:iam/role:Role                                       urn:pulumi:dev::workload::pkg:main:PackerIntegration$aws:iam/role:Role::PackerBuilderEcs
aws:acm/certificate:Certificate                         urn:pulumi:dev::workload::pkg:main:ACMCertificate$aws:acm/certificate:Certificate::api-cert
aws:ecr/repository:Repository                           urn:pulumi:dev::workload::pkg:containers:Registry$aws:ecr/repository:Repository::myapp/myapp
pulumi:providers:random                                 urn:pulumi:dev::workload::pulumi:providers:random::default
aws:rds/subnetGroup:SubnetGroup                         urn:pulumi:dev::workload::pkg:main:TemporalDatabase$aws:rds/subnetGroup:SubnetGroup::dev-temporal-subnet-group
random:index/randomPassword:RandomPassword              urn:pulumi:dev::workload::pkg:main:TemporalDatabase$random:index/randomPassword:RandomPassword::dev-db-user-temporal-password
aws:eks/cluster:Cluster                                 urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:eks/cluster:Cluster::dev-eks
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:iam/rolePolicyAttachment:RolePolicyAttachment::rpa-1
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:iam/rolePolicyAttachment:RolePolicyAttachment::ngpa-2
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:iam/rolePolicyAttachment:RolePolicyAttachment::rpa-0
aws:iam/role:Role                                       urn:pulumi:dev::workload::pkg:main:PackerIntegration$aws:iam/role:Role::PackerTool
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:iam/rolePolicyAttachment:RolePolicyAttachment::ngpa-0
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:iam/rolePolicyAttachment:RolePolicyAttachment::ngpa-1
aws:iam/instanceProfile:InstanceProfile                 urn:pulumi:dev::workload::pkg:main:PackerIntegration$aws:iam/instanceProfile:InstanceProfile::PackerBuilderEcs
aws:rds/instance:Instance                               urn:pulumi:dev::workload::pkg:main:TemporalDatabase$aws:rds/instance:Instance::dev-temporal-db-instance
aws:ec2/launchTemplate:LaunchTemplate                   urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:ec2/launchTemplate:LaunchTemplate::dev-ng-launch-template
aws:iam/policy:Policy                                   urn:pulumi:dev::workload::aws:iam/policy:Policy::DatadogIntegrationPolicy
pulumi:providers:mysql                                  urn:pulumi:dev::workload::pkg:main:TemporalDatabase$pulumi:providers:mysql::dev-temporal-db-provider
aws:eks/nodeGroup:NodeGroup                             urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pkg:main:eksState$aws:eks/nodeGroup:NodeGroup::dev-node-group
mysql:index/database:Database                           urn:pulumi:dev::workload::pkg:main:TemporalDatabase$mysql:index/database:Database::dev-temporal-db-temporal_visibility
mysql:index/database:Database                           urn:pulumi:dev::workload::pkg:main:TemporalDatabase$mysql:index/database:Database::dev-temporal-db-temporal
mysql:index/user:User                                   urn:pulumi:dev::workload::pkg:main:TemporalDatabase$mysql:index/user:User::dev-temporal-db-user-temporal-remote
pulumi:providers:kubernetes                             urn:pulumi:dev::workload::pkg:main:KubernetesCluster$pulumi:providers:kubernetes::k8sprovider
kubernetes:core/v1:Secret                               urn:pulumi:dev::workload::pkg:main:TemporalDatabase$kubernetes:core/v1:Secret::dev-temporal-db-password
kubernetes:core/v1:Namespace                            urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:core/v1:Namespace::dev-myapp
kubernetes:core/v1:Namespace                            urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:core/v1:Namespace::dev-temporal
kubernetes:core/v1:ConfigMap                            urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:core/v1:ConfigMap::dev-aws-auth
kubernetes:helm.sh/v3:Release                           urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:helm.sh/v3:Release::dev-datadog-agent
kubernetes:core/v1:Namespace                            urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:core/v1:Namespace::dev-evan
kubernetes:core/v1:Namespace                            urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:core/v1:Namespace::dev-doug
mysql:index/grant:Grant                                 urn:pulumi:dev::workload::pkg:main:TemporalDatabase$mysql:index/database:Database$mysql:index/grant:Grant::dev-temporal-grant-temporal-temporal_visibility
mysql:index/grant:Grant                                 urn:pulumi:dev::workload::pkg:main:TemporalDatabase$mysql:index/database:Database$mysql:index/grant:Grant::dev-temporal-grant-temporal-temporal
aws:iam/openIdConnectProvider:OpenIdConnectProvider     urn:pulumi:dev::workload::pkg:main:KubernetesCluster$aws:iam/openIdConnectProvider:OpenIdConnectProvider::dev-oidc-provider
aws:iam/role:Role                                       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$aws:iam/role:Role::dev-aws-lb-controller
aws:iam/role:Role                                       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$aws:iam/role:Role::dev-myapp-control-plane
kubernetes:core/v1:ServiceAccount                       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:core/v1:ServiceAccount::dev-aws-lb-controller
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::aws:iam/rolePolicyAttachment:RolePolicyAttachment::myapp-control-plane-ec2-read
kubernetes:core/v1:ServiceAccount                       urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:core/v1:ServiceAccount::dev-myapp-control-plane
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::aws:iam/rolePolicyAttachment:RolePolicyAttachment::myapp-control-plane-s3-state
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::aws:iam/rolePolicyAttachment:RolePolicyAttachment::myapp-control-plane-key-policy
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::aws:iam/rolePolicyAttachment:RolePolicyAttachment::myapp-control-plane-iam-auth
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::aws:iam/rolePolicyAttachment:RolePolicyAttachment::myapp-control-plane-route53-full
aws:iam/rolePolicyAttachment:RolePolicyAttachment       urn:pulumi:dev::workload::aws:iam/rolePolicyAttachment:RolePolicyAttachment::myapp-control-plane-tentant-infrastructure
kubernetes:helm.sh/v3:Release                           urn:pulumi:dev::workload::pkg:main:KubernetesCluster$kubernetes:helm.sh/v3:Release::dev-aws-lb-controller

Found no pending operations associated with dev

Backend
Name           Brendans-MBP.lan
URL            s3://myapp-pulumi-state-274d90a/workload?region=us-west-2&awssdk=v2&profile=shared-infra-prod.admin
User           bfosberry
Organizations

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-aws/sdk/v5         5.35.0
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.24.3
github.com/pulumi/pulumi-mysql/sdk/v3       3.1.0
github.com/pulumi/pulumi/sdk/v3             3.55.0
github.com/myapp/infra/pulumi/lib           0.0.0

Pulumi locates its logs in /var/folders/2g/6nmqw74d53b1hjcl530_0vw00000gn/T/ by default

### Additional context

The error returned when creating an integration without a role is

```
  datadog:aws:Integration (myapp-workload-dev-integration):
    error: expected non-nil error with nil state during Create of urn:pulumi:dev::workload::datadog:aws/integration:Integration::myapp-workload-dev-integration
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@bfosberry thanks for reporting this. It looks like this is the same as this upstream issue: 
- https://github.com/DataDog/terraform-provider-datadog/issues/1981

Definitely seems like there's a catch-22 here: the aws.iam.Role requires an external ID to be secure, the datadog.aws.Integration requires a role to have access. Having a momentary "wide open" policy is not great.

Our hands are usually a little tied on addressing upstream bugs, but I'll see if I can escalate this with our contacts at Datadog, and recommend you do the same with the upstream issue.

**Comment by nivinjoseph** [comment]
I had this issue with "@pulumi/datadog": "4.19.1" nodejs package. I resolved by downgrading to "@pulumi/datadog": "4.18.1" nodejs package.

**Comment by bfosberry** [comment]
The linked issue was resolved by the user using an unscoped key. Im using an unscoped key to begin with so I suspect that was a different issue

**Comment by bfosberry** [comment]
I updated to v3.75.0 and I no longer see this issue, this pulled in an upstream version update for tf.
