### ISSUE TITLE
package not found on yarn

### ISSUE THREAD

**Issue by mxtopher** [pulumi/pulumi-datadog#314]
### What happened?

yarn can't find @pulumi/datadog:

~ yarn add @pulumi/datadog
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@pulumi%2fdatadog: Not found".
info If you think this is a bug, please open a bug report with the information provided in "[irrelevant]/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Expected Behavior

It should be installed successfully. It is installed on our ci builds with no issues, but started 404ing today.

### Steps to reproduce

~ yarn add @pulumi/datadog
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@pulumi%2fdatadog: Not found".
info If you think this is a bug, please open a bug report with the information provided in "[irrelevant]/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Host     
OS       darwin
Version  13.4.1
Arch     arm64

Backend        
Name           QK3P7Y619V
URL            file://~/.pulumi/local
User           cmoreiradasilva
Organizations

### Additional context

It seems to be up on npm, it is likely a yarn issue. IDK where to report it other than here though.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sfc-gh-cmoreiradasilva** [comment]
It is back. It was probably a transient issue. Sorry for the noise.

**Comment by iwahbe** [comment]
No problem. Please let us know if you can't find `@pulumi/datadog` at any point in the future.
