### ISSUE TITLE
The resourceCollectionEnabled setting does not work

### ISSUE THREAD

**Issue by runlevel5** [pulumi/pulumi-datadog#520]
### What happened?

The `resourceCollectionEnabled` does not work as expected.

### Example

Here is my code:

```ts
const awsDatadogIntegration = new datadog.aws.Integration('aws-datadog-integration', {
      accountId: accountId,
      roleName: 'datadogIntegrationRole',
      resourceCollectionEnabled: 'true',
      })
 ```
 
 then apply with `pulumi up` and double-check to see the setting has been toggled or not in Datadog Web Console.
 
Expected: The toggle is set to Enabled
Actual: The toggle is still sitting as Disabled

### Output of `pulumi about`

```
% pulumi about
CLI
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/Users/tle/.asdf/shims/node' version='v20.11.1'
```

The `@pulumi/datadog` is `4.27.0`

### Additional context

I have not verified whether this might be the bug of upstream 3.38 tf plugin driver.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @runlevel5. Thanks for raising this issue and providing a clear repro. We'll take a look as soon as possible.

**Comment by iwahbe** [comment]
Hi @runlevel5. That property has been deprecated in the latest version of this provider. Can you upgrade to [pulumi-datadog v4.28.0](https://github.com/pulumi/pulumi-datadog/releases/tag/v4.28.0) and try again? `resourceCollectionEnabled` has been deprecated in favor of `extendedResourceCollectionEnable`.

**Comment by runlevel5** [comment]
Great thanks. I confirm the 4.28 fixed the issue.
