### ISSUE TITLE
Update to terraform-provider-datadog 2.13.0

### ISSUE THREAD

**Issue by XBeg9** [pulumi/pulumi-datadog#85]
https://github.com/pulumi/pulumi-datadog/blob/726371ecb509a928e7fe64c609667b39dbed67da/provider/go.sum#L551

Could you please update it to https://github.com/DataDog/terraform-provider-datadog/releases/tag/v2.13.0 ? 

Thanks

**Comment by stack72** [comment]
Hi @XBeg9 

This provider was upgraded already as part of v2.8.0

Can you tell me if this isn't the case?

Paul
